### ISSUE TITLE
Note on CSS shadows

### ISSUE THREAD

**Issue by jfroelich** [jfroelich/rss-reader#70]
Copied from old notes. Shadow effect on articles with a bit of spacing (specifying in order the horizontal offset, vertical offset, optional blur distance and optional spread 
distance of the shadow), an optional color value and an optional ‘inset‘ keyword (to create an inner shadow, rather than the default outer shadow).

``` css
#example1 {
-moz-box-shadow: 10px 10px 5px #888;
-webkit-box-shadow: 10px 10px 5px #888;
box-shadow: 10px 10px 5px #888;
}
.shadow {
-moz-box-shadow: 0 0 30px 5px #999;
-webkit-box-shadow: 0 0 30px 5px #999;
}

.box_round {
  -webkit-border-radius: 12px; /* Android = 1.6, iOS 1-3.2, Safari 3-4 */
          border-radius: 12px; /* Android 2.1+, Chrome, Firefox 4+, IE 9+, iOS 4+, Opera 10.50+, Safari 5+ */
  /* useful if you don't want a bg color from leaking outside the border: */
  -webkit-background-clip: padding-box; background-clip: padding-box;
}
```
